services:
  db:
    image: postgres:latest
    container_name: psql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  api:
    image: django_api
    container_name: django_api
    volumes:
      - $PWD:/code
    build:
      dockerfile: src/api/Dockerfile 
    ports:
      - "8000:8000"
    entrypoint: ["/bin/sh", "/code/entrypoint.sh"]
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - HOST_HOSTNAME=${HOST_HOSTNAME}

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6380:6379"

  nginx:
    image: nginx
    container_name: nginx
    build:
      dockerfile: src/nginx/Dockerfile
    ports:
      - "8443:443"

volumes:
  postgres_data:
